#!/usr/bin/env python3
"""jqa_violations_report.py

Parses jqa-analyze.log and produces a structured Markdown report of
jQAssistant constraint violations with architectural and engineering context.

Output: 05_deliver/input/01_ingest/jqa-violations-report.md

This is an INTERNAL document — it is not intended for external distribution.
It surfaces structural weaknesses in the analysed codebase for the engineering team.

Usage:
    python 01_ingest/jqassistant/scripts/jqa_violations_report.py
    python 01_ingest/jqassistant/scripts/jqa_violations_report.py --log path/to/jqa-analyze.log
    python 01_ingest/jqassistant/scripts/jqa_violations_report.py --out path/to/report.md
"""

import re
import sys
import argparse
from pathlib import Path
from datetime import datetime

# ---------------------------------------------------------------------------
# Architectural context — loaded from constraint-context.yaml if present,
# generated by jqa_generate_rules.py.  Falls back to empty dict so the
# report still runs on any project that hasn't run Phase 7 yet.
# ---------------------------------------------------------------------------

_SCRIPT_DIR = Path(__file__).resolve().parent
_CONTEXT_YAML = _SCRIPT_DIR.parent / "config" / "constraint-context.yaml"

try:
    import yaml as _yaml
    _YAML_AVAILABLE = True
except ImportError:
    _YAML_AVAILABLE = False

if _YAML_AVAILABLE and _CONTEXT_YAML.exists():
    CONSTRAINT_CONTEXT = _yaml.safe_load(_CONTEXT_YAML.read_text(encoding="utf-8")) or {}
else:
    CONSTRAINT_CONTEXT = {}

# ---------------------------------------------------------------------------
# LEGACY — kept only so existing handwritten context entries remain usable
# if layers.yaml / constraint-context.yaml have not yet been generated.
# Merged below; generated entries take priority.
# ---------------------------------------------------------------------------

_LEGACY_CONTEXT = {}

# Merge: generated YAML takes priority; legacy fills gaps
for _k, _v in _LEGACY_CONTEXT.items():
    CONSTRAINT_CONTEXT.setdefault(_k, _v)


SEVERITY_BADGE = {
    "CRITICAL": "🔴 CRITICAL",
    "MAJOR":    "🟠 MAJOR",
    "MINOR":    "🟡 MINOR",
    "INFO":     "🔵 INFO",
}

# ---------------------------------------------------------------------------
# Log line reconstruction
# Docker container output may be terminal-wrapped when captured via Tee-Object.
# Lines that don't begin with a timestamp are continuations of the previous line.
# ---------------------------------------------------------------------------

_TIMESTAMP_PAT = re.compile(r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+ ")
_LOG_PREFIX_PAT = re.compile(
    r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+ \[.*?\] \w+\s+\S+\s+-\s*"
)


def reconstruct_lines(raw_text: str) -> list[str]:
    """
    Reconstruct logical log lines from terminal-wrapped Docker output.
    Continuation lines (no leading timestamp) are appended to the preceding line.
    """
    result = []
    buffer = ""
    for line in raw_text.splitlines():
        if _TIMESTAMP_PAT.match(line):
            if buffer:
                result.append(buffer)
            buffer = line
        else:
            stripped = line.strip()
            if stripped and buffer:
                buffer = buffer.rstrip() + " " + stripped
            elif stripped:
                buffer = stripped
    if buffer:
        result.append(buffer)
    return result


def extract_message(line: str) -> str:
    """Strip timestamp + log-level prefix, return the bare message."""
    m = _LOG_PREFIX_PAT.match(line)
    if m:
        return line[m.end():].strip()
    return line.strip()


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def parse_violations(logical_messages: list[str]) -> list[dict]:
    """
    Extract all constraint violation blocks.
    Returns list of dicts: constraint, severity, rows, description, violations.
    """
    blocks = []
    i = 0
    while i < len(logical_messages):
        msg = logical_messages[i]
        if "--[ Constraint Violation" in msg:
            block: dict = {"description_parts": [], "violations": []}
            i += 1
            while i < len(logical_messages):
                m = logical_messages[i]
                # End-of-block separator (long dash line)
                if re.match(r"-{15,}\s*$", m):
                    i += 1
                    break
                if m.startswith("Constraint:"):
                    block["constraint"] = m.split(":", 1)[1].strip()
                elif m.startswith("Severity:"):
                    block["severity"] = m.split(":", 1)[1].strip()
                elif m.startswith("Number of rows:"):
                    block["rows"] = int(m.split(":", 1)[1].strip())
                elif "violatingJar=" in m:
                    block["violations"].append(m)
                elif m and not re.match(r"-{5,}", m):
                    block["description_parts"].append(m)
                i += 1
            block["description"] = " ".join(block.pop("description_parts", [])).strip()
            block.setdefault("constraint", "Unknown")
            block.setdefault("severity", "UNKNOWN")
            block.setdefault("rows", len(block["violations"]))
            blocks.append(block)
        else:
            i += 1
    return blocks


_RULE_ID_PAT = r"'([A-Za-z0-9]+:[A-Za-z0-9_]+)'"


def parse_concepts_applied(messages: list[str]) -> list[str]:
    found = set()
    for m in messages:
        hit = re.search(r"Concept " + _RULE_ID_PAT + r" has already been applied", m)
        if hit:
            found.add(hit.group(1))
        hit2 = re.search(r"Applying concept " + _RULE_ID_PAT, m)
        if hit2:
            found.add(hit2.group(1))
    return sorted(found)


def parse_constraints_validated(messages: list[str]) -> list[tuple[str, str]]:
    seen = {}
    for m in messages:
        hit = re.search(r"Validating constraint " + _RULE_ID_PAT + r" with severity: '(\w+)'", m)
        if hit:
            seen[hit.group(1)] = hit.group(2)
    return sorted(seen.items())


def parse_summary(messages: list[str]) -> tuple[int, int]:
    for m in messages:
        hit = re.search(r"Failed rules detected:\s*(\d+) concepts?,\s*(\d+) constraints?", m)
        if hit:
            return int(hit.group(1)), int(hit.group(2))
    return 0, 0


def parse_violation_row(raw: str) -> dict:
    """Parse: violatingJar=X, forbiddenDependency=Y, forbiddenLayer=Z"""
    parts = {}
    for kv in re.split(r",\s*", raw):
        if "=" in kv:
            k, v = kv.split("=", 1)
            parts[k.strip()] = v.strip()
    return parts


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------

def generate_report(log_path: Path) -> str:
    # Tee-Object on Windows PS5 defaults to UTF-16 LE; detect and handle both
    raw_bytes = log_path.read_bytes()
    if raw_bytes[:2] in (b'\xff\xfe', b'\xfe\xff'):
        raw_text = raw_bytes.decode("utf-16", errors="replace")
    else:
        raw_text = raw_bytes.decode("utf-8", errors="replace")
    logical_lines = reconstruct_lines(raw_text)
    messages = [extract_message(ln) for ln in logical_lines]

    violations = parse_violations(messages)
    concepts_applied = parse_concepts_applied(messages)
    constraints_validated = parse_constraints_validated(messages)
    _failed_concepts, failed_constraints = parse_summary(messages)

    run_ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    L = []

    def line(s=""):
        L.append(s)

    line("# jQAssistant Architecture Health Report")
    line()
    line(f"> **Generated:** {run_ts}  ")
    line(f"> **Source log:** `{log_path.name}`  ")
    # Derive the rule group from the first validated constraint's namespace
    _detected_group = "unknown"
    if constraints_validated:
        _ns = constraints_validated[0][0].split(":")[0]
        _detected_group = f"{_ns}:Default"
    line(f"> **Rule group:** `{_detected_group}`  ")
    line(f"> **Target:** `{log_path.parent}`")
    line()
    line("> ⚠️  **Internal document** — not for external distribution.")
    line("> This report surfaces structural weaknesses in the analysed codebase for the engineering team.")
    line()
    line("---")
    line()

    # ── Executive summary ────────────────────────────────────────
    line("## Summary")
    line()
    if not violations:
        line(f"✅ **No constraint violations detected.** All `{_detected_group}` architectural layer rules pass.")
    else:
        total_rows = sum(v["rows"] for v in violations)
        line(
            f"**{len(violations)} constraint(s) violated** "
            f"({total_rows} individual dependency violation(s) across the analysed codebase)."
        )
        line()
        line("| Constraint | Severity | Violations |")
        line("|---|---|:---:|")
        for v in violations:
            badge = SEVERITY_BADGE.get(v["severity"], v["severity"])
            line(f"| `{v['constraint']}` | {badge} | {v['rows']} |")
    line()

    # ── Concepts applied ─────────────────────────────────────────
    if concepts_applied:
        line("---")
        line()
        line("## Concepts Applied")
        line()
        line(
            "The following structural labels were successfully written to the graph "
            "(idempotent — safe to re-run):"
        )
        line()
        for c in concepts_applied:
            line(f"- `{c}`")
        line()

    # ── Constraints evaluated ────────────────────────────────────
    if constraints_validated:
        line("---")
        line()
        line("## Constraints Evaluated")
        line()
        line("| Constraint | Severity | Result |")
        line("|---|---|:---:|")
        for name, sev in constraints_validated:
            badge = SEVERITY_BADGE.get(sev, sev)
            failed = any(v["constraint"] == name for v in violations)
            status = "❌ FAILED" if failed else "✅ PASSED"
            line(f"| `{name}` | {badge} | {status} |")
        line()

    # ── Violation detail ─────────────────────────────────────────
    if violations:
        line("---")
        line()
        line("## Violation Detail")
        line()
        line(
            "Each section below describes a violated constraint, explains why it matters from both an "
            "architectural and a practical engineering standpoint, and lists the specific dependencies "
            "that break the rule."
        )
        line()

        for v in violations:
            badge = SEVERITY_BADGE.get(v["severity"], v["severity"])
            line(f"### `{v['constraint']}`")
            line()
            ctx = CONSTRAINT_CONTEXT.get(v["constraint"])
            if ctx:
                line(f"**Rule:** {ctx['rule']}  ")
                line(f"**Direction violated:** {ctx['layers_involved']}  ")
            elif v.get("description"):
                line(f"**Rule:** {v['description']}  ")
            line(f"**Severity:** {badge}  ")
            line(f"**Violations:** {v['rows']}")
            line()

            if ctx:
                line("#### Why this matters architecturally")
                line()
                line(ctx["arch_why"])
                line()
                line("#### Practical engineering impact")
                line()
                line(ctx["practical_impact"])
                line()

            if v["violations"]:
                line("#### Violating dependencies")
                line()
                parsed_rows = [parse_violation_row(r) for r in v["violations"]]
                all_keys: list[str] = []
                for row in parsed_rows:
                    for k in row:
                        if k not in all_keys:
                            all_keys.append(k)
                if all_keys:
                    line("| " + " | ".join(all_keys) + " |")
                    line("| " + " | ".join(["---"] * len(all_keys)) + " |")
                    for row in parsed_rows:
                        cells = " | ".join(f"`{row.get(k, '')}`" for k in all_keys)
                        line(f"| {cells} |")
                else:
                    for r in v["violations"]:
                        line(f"- `{r}`")
                line()

    # ── Clean pass ───────────────────────────────────────────────
    if not violations:
        line("---")
        line()
        line("## Layer Health — All constraints pass")
        line()
        if constraints_validated:
            line("```")
            for name, sev in constraints_validated:
                layer = name.split(":", 1)[1] if ":" in name else name
                line(f"  {layer:<45} ✅  no upward dependencies")
            line("```")
        else:
            line("All evaluated layer constraints passed.")
        line()

    line("---")
    line()
    line("*Report generated by Archim8 · `jqa_violations_report.py`*")
    line()

    return "\n".join(L)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Parse jqa-analyze.log and produce a structured architecture health report."
    )
    parser.add_argument(
        "--log",
        default=None,
        help="Path to jqa-analyze.log (default: auto-resolved from script location).",
    )
    parser.add_argument(
        "--out",
        default=None,
        help="Output path for the Markdown report (default: jqa-violations-report.md alongside the log).",
    )
    args = parser.parse_args()

    if args.log:
        log_path = Path(args.log).resolve()
    else:
        script_dir = Path(__file__).resolve().parent
        # scripts/ → jqassistant/ → 01_ingest/ → arcroot/
        arc_root = script_dir.parents[2]
        log_path = arc_root / "05_deliver" / "input" / "01_ingest" / "jqa-analyze.log"

    if not log_path.exists():
        print(f"ERROR: Log file not found: {log_path}", file=sys.stderr)
        sys.exit(1)

    out_path = Path(args.out).resolve() if args.out else log_path.parent / "jqa-violations-report.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    report = generate_report(log_path)
    out_path.write_text(report, encoding="utf-8")
    print(f"  Violations report:       {out_path}")


if __name__ == "__main__":
    main()
